import { MarketType } from "./signal";

export const MARKETS = ["crypto", "forex", "stocks"] as const;
export type Market = (typeof MARKETS)[number];

export type MarketDataType = {
  id: string;
  community_id: string;
  market: MarketType;
};

export const MARKET_ASSETS: Record<MarketType, string[]> = {
  forex: [
    "EUR/USD",
    "GBP/USD",
    "USD/JPY",
    "USD/CHF",
    "AUD/USD",
    "NZD/USD",
    "USD/CAD",
    "EUR/GBP",
    "EUR/JPY",
    "EUR/CHF",
    "EUR/AUD",
    "EUR/NZD",
    "EUR/CAD",
    "GBP/JPY",
    "GBP/CHF",
    "GBP/AUD",
    "GBP/NZD",
    "GBP/CAD",
    "AUD/JPY",
    "AUD/NZD",
    "AUD/CAD",
    "AUD/CHF",
    "NZD/JPY",
    "NZD/CHF",
    "NZD/CAD",
    "CAD/JPY",
    "CAD/CHF",
    "CHF/JPY",
    "USD/SGD",
    "USD/HKD",
    "USD/MXN",
    "USD/ZAR",
    "USD/TRY",
    "USD/SEK",
    "USD/NOK",
    "USD/DKK",
    "XAU/USD",
    "XAG/USD",
  ],
  crypto: [
    "BTC/USDT",
    "ETH/USDT",
    "SOL/USDT",
    "BNB/USDT",
    "XRP/USDT",
    "ADA/USDT",
    "DOGE/USDT",
    "AVAX/USDT",
    "LINK/USDT",
    "MATIC/USDT",
    "DOT/USDT",
    "LTC/USDT",
    "BCH/USDT",
    "TRX/USDT",
    "ATOM/USDT",
    "NEAR/USDT",
    "TON/USDT",
    "OP/USDT",
    "ARB/USDT",
    "FIL/USDT",
    "APT/USDT",
    "SUI/USDT",
    "INJ/USDT",
    "RENDER/USDT",
  ],
  stocks: [
    "AAPL",
    "MSFT",
    "NVDA",
    "AMZN",
    "GOOGL",
    "META",
    "TSLA",
    "NFLX",
    "AMD",
    "INTC",
    "AVGO",
    "QCOM",
    "TSM",
    "ASML",
    "MU",
    "ADBE",
    "CRM",
    "ORCL",
    "IBM",
    "SHOP",
    "SAP",
    "SNOW",
    "PLTR",
    "PYPL",
    "UBER",
    "ABNB",
    "JPM",
    "BAC",
    "WFC",
    "GS",
    "MS",
    "V",
    "MA",
    "DIS",
    "KO",
    "PEP",
    "WMT",
    "COST",
    "NKE",
    "MCD",
    "XOM",
    "CVX",
  ],
};
